name: tests

on:
  push:
    branches:
      - develop
      - main
      - workos
  pull_request:
    branches:
      - develop
      - main
      - workos

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: travel-guide_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Node Dependencies
        run: pnpm install

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.ci .env.testing

      - name: Generate Application Key
        run: php artisan key:generate --env=testing

      - name: Debug MySQL Connection
        run: |
          apt-get update && apt-get install -y netcat
          nc -zv 127.0.0.1 3306

      - name: Run Migrations
        run: php artisan migrate --env=testing --force --no-interaction

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Build Assets
        run: pnpm build

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --memory-limit=512M

      - name: Run Tests
        run: ./vendor/bin/pest